export const PROJECTS = [
    {
        title: 'Iweft Dashboard',
        image_path: '/projects/iweft-dashboard.png',
        desc: `An admin dashboard for managing the Iweft laundry app, providing administrative 
        tools to oversee user accounts, monitor order statuses, and manage service offerings.
        The dashboard includes analytics features to track performance metrics, streamline operations,
        and enhance customer service efficiency.`,
        techs: [
            'Typescript',
            'Express JS',
            'Socket.io',
            'React JS',
            'Stripe',
            'MongoDB',
            'Zod',
            'React Query',
            'Cloundinary',
            'Vite',
            'Tailwind CSS',
            'Daisy UI',
            'React Hook Form',
            'Zustand',
        ],
        link: 'https://admin.iweft.com/',
    },

    {
        title: 'Iweft Landing Page',
        image_path: '/projects/iweft-landing.png',
        desc: `A laundry app designed specifically for Dubai, allowing users to effortlessly schedule laundry pickups, 
        track their orders in real time, and make secure payments. Iweft offers a wide range of laundry services,
        including dry cleaning and eco-friendly options, enhancing convenience for both residents and tourists.
        Experience seamless laundry management by downloading the app from the App Store—simply scan the QR code on the landing page.`,
        techs: ['Typescript', 'React JS', 'Zod', 'React Query', 'Vite', 'Tailwind CSS', 'Daisy UI'],
        link: 'https://iweft.onrender.com/',
    },

    {
        title: 'Imotor',
        image_path: '/projects/imotor.app.png',
        desc: `A Dubai-based platform for buying and selling cars, boats, and trucks, offering a user-friendly interface for seamless transactions. Users can browse a wide selection of vehicles, post listings, and connect with potential buyers or sellers. The platform aims to simplify the process of vehicle trading, providing essential features like detailed listings, price comparisons, and secure payment options.`,
        techs: [
            'Javascript',
            'React JS',
            'Zod',
            'React Query',
            'Vite',
            'Material UI',
            'Stripe',
            'Socket.io',
            'React Hook Form',
            'Zustand',
        ],
        link: 'https://imotor-app.onrender.com/',
    },

    {
        title: 'Materna Connect',
        image_path: '/projects/maternaconnect.png',
        desc: `A web application for booking maternity checkup appointments, enhancing the scheduling experience for expectant mothers. The app includes an intuitive interface that allows users to view available time slots, engage in real-time chats with healthcare providers, and manage their appointments effortlessly, ensuring a smooth and convenient experience.`,
        techs: [
            'Javascript',
            'React JS',
            'Zod',
            'React Query',
            'Vite',
            'Material UI',
            'Socket.io',
            'React Hook Form',
            'Zustand',
            'Calendar JS',
            'Cloundinary',
        ],
        link: 'https://maternaconnect.onrender.com/',
    },

    {
        title: 'Materna Connect ADMIN',
        image_path: '/projects/maternaconnect-admin.png',
        desc: `An admin dashboard for managing maternity checkup appointments, providing healthcare administrators with tools to oversee scheduling, track user engagement, and manage profiles. The dashboard features analytics for monitoring appointment trends, ensuring efficient operations and improved service delivery.`,
        techs: [
            'Javascript',
            'React JS',
            'Zod',
            'React Query',
            'Vite',
            'Material UI',
            'Socket.io',
            'React Hook Form',
            'Zustand',
            'Calendar JS',
            'Cloundinary',
        ],

        link: 'https://materna-connect-admin.onrender.com/',
    },

    {
        title: 'ADAP-HUB',
        image_path: '/projects/adap-hub.png',
        desc: `Developed an online profiling platform for the ADAP organization in Davao City, designed to empower Persons with Disabilities (PWD). The platform allows users to create profiles, access essential resources, and connect with support services, fostering a more inclusive community and enhancing opportunities for PWD.`,
        techs: [
            'Javascript',
            'React Native',
            'Expo',
            'Express JS',
            'MongoDB',
            'Socket.io',
            'React Hook Form',
            'Zustand',
            'React Query',
        ],

        link: 'https://play.google.com/store/apps/details?id=com.saure1423.adaphub',
    },

    {
        title: 'ADAP-HUB ADMIN',
        image_path: '/projects/adaphub-admin.png',
        desc: `Admin dashboard for the ADAP HUB application, equipping administrators with tools to manage user profiles, monitor engagement, and oversee resources available to Persons with Disabilities (PWD). The dashboard features analytics for tracking usage trends and ensuring effective support services, enhancing the overall management of the platform.`,
        techs: [
            'Javascript',
            'React JS',
            'Zod',
            'React Query',
            'Vite',
            'Material UI',
            'Socket.io',
            'React Hook Form',
            'Zustand',
            'Calendar JS',
            'Cloundinary',
        ],
        link: 'https://adap-hub-admin.onrender.com/',
    },
];
